package main

var (
	keyBindings = [][3]string{
		[3]string{`A`, `A`, ``},
		[3]string{`B`, `B`, ``},
		[3]string{`C`, `C`, ``},
		[3]string{`D`, `D`, ``},
		[3]string{`E`, `E`, ``},
		[3]string{`F`, `F`, ``},
		[3]string{`G`, `G`, ``},
		[3]string{`H`, `H`, ``},
		[3]string{`I`, `I`, ``},
		[3]string{`J`, `J`, ``},
		[3]string{`K`, `K`, ``},
		[3]string{`L`, `L`, ``},
		[3]string{`M`, `M`, ``},
		[3]string{`N`, `N`, ``},
		[3]string{`O`, `O`, ``},
		[3]string{`P`, `P`, ``},
		[3]string{`Q`, `Q`, ``},
		[3]string{`R`, `R`, ``},
		[3]string{`S`, `S`, ``},
		[3]string{`T`, `T`, ``},
		[3]string{`W`, `W`, ``},
		[3]string{`Y`, `Y`, ``},
		[3]string{`Z`, `Z`, ``},
		[3]string{`a`, `a`, ``},
		[3]string{`b`, `b`, ``},
		[3]string{`c`, `c`, ``},
		[3]string{`d`, `d`, ``},
		[3]string{`e`, `e`, ``},
		[3]string{`f`, `f`, ``},
		[3]string{`g`, `g`, ``},
		[3]string{`h`, `h`, ``},
		[3]string{`i`, `i`, ``},
		[3]string{`j`, `j`, ``},
		[3]string{`k`, `k`, ``},
		[3]string{`l`, `l`, ``},
		[3]string{`m`, `m`, ``},
		[3]string{`n`, `n`, ``},
		[3]string{`o`, `o`, ``},
		[3]string{`p`, `p`, ``},
		[3]string{`q`, `q`, ``},
		[3]string{`r`, `r`, ``},
		[3]string{`s`, `s`, ``},
		[3]string{`t`, `t`, ``},
		[3]string{`u`, `u`, ``},
		[3]string{`w`, `w`, ``},
		[3]string{`x`, `x`, ``},
		[3]string{`y`, `y`, ``},
		[3]string{`z`, `z`, ``},
		[3]string{`1`, `1`, ``},
		[3]string{`2`, `2`, ``},
		[3]string{`3`, `3`, ``},
		[3]string{`4`, `4`, ``},
		[3]string{`5`, `5`, ``},
		[3]string{`6`, `6`, ``},
		[3]string{`7`, `7`, ``},
		[3]string{`8`, `8`, ``},
		[3]string{`9`, `9`, ``},
		[3]string{`0`, `0`, ``},
	}

	punctBindings = [][3]string{
		[3]string{`(`, `(`, ``},
		[3]string{`)`, `)`, ``},
		[3]string{`,`, `,`, ``},
		[3]string{`.`, `\ldots`, `...`},
	}

	connBindings = [][3]string{
		[3]string{`V`, `\vee`, "\u2228"},
		[3]string{`v`, `\vee`, "\u2228"},
		[3]string{`-`, `\neg`, "\u00ac"},
		[3]string{`^`, `\wedge`, "\u2227"},
		[3]string{`>`, `\supset`, "\u2283"},
	}

	plBindings = [][3]string{
		[3]string{`U`, `\forall`, "\u2200"},
		[3]string{`X`, `\exists`, "\u2203"},
		[3]string{"=", "=", ""},
	}

	turnstileBindings = [][3]string{
		[3]string{`|-`, `\vdash`, "⊢"},
	}

	greekBindings = [][3]string{
		[3]string{`\A`, `A`, ""},
		[3]string{`\B`, `B`, `B`},
		[3]string{`\G`, `\Gamma`, "\u0393"},
		[3]string{`\D`, `\Delta`, "\u0394"},
		[3]string{`\E`, `E`, "E"},
		[3]string{`\Z`, `Z`, "Z"},
		[3]string{`\T`, `\Theta`, "\u0398"},
		[3]string{`\L`, `\Lambda`, "\u039b"},
		[3]string{`\M`, `M`, "M"},
		[3]string{`\N`, `N`, "N"},
		[3]string{`\X`, `\Xi`, "\u039e"},
		[3]string{`\P`, `\Pi`, "\u03a0"},
		[3]string{`\R`, `\Rho`, "\u03a1"},
		[3]string{`\S`, `\Sigma`, "\u03a3"},
		[3]string{`\U`, `\Upsilon`, "\u03a5"},
		[3]string{`\F`, `\Phi`, "\u03a6"},
		[3]string{`\Q`, `\Psi`, "\u03a8"},
		[3]string{`\W`, `\Omega`, "\u03a9"},
		[3]string{`\a`, `\alpha`, "\u03b1"},
		[3]string{`\b`, `\beta`, "\u03b2"},
		[3]string{`\g`, `\gamma`, "\u03b3"},
		[3]string{`\d`, `\delta`, "\u03b4"},
		[3]string{`\e`, `\epsilon`, "\u03b5"},
		[3]string{`\z`, `\zeta`, "\u03b6"},
		[3]string{`\h`, `\eta`, "\u03b7"},
		[3]string{`\t`, `\theta`, "\u03b8"},
		[3]string{`\i`, `\iota`, "\u03b9"},
		[3]string{`\k`, `\kappa`, "\u03ba"},
		[3]string{`\l`, `\lambda`, "\u03bb"},
		[3]string{`\m`, `\mu`, "\u03bc"},
		[3]string{`\n`, `\nu`, "\u03bd"},
		[3]string{`\x`, `\xi`, "\u03be"},
		[3]string{`\o`, `\omicron`, "\u03bf"},
		[3]string{`\p`, `\pi`, "\u03c0"},
		[3]string{`\r`, `\rho`, "\u03c1"},
		[3]string{`\s`, `\sigma`, "\u03c3"},
		[3]string{`\y`, `\tau`, "\u03c4"},
		[3]string{`\u`, `\upsilon`, "\u03c5"},
		[3]string{`\f`, `\varphi`, "\u03c6"},
		[3]string{`\c`, `\chi`, "\u03c7"},
		[3]string{`\q`, `\psi`, "\u03c8"},
		[3]string{`\w`, `\omega`, "\u03c9"},
	}
)
