// Code generated by "stringer -type logicalConstant"; DO NOT EDIT.

package gentzen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Neg-1]
	_ = x[Conj-2]
	_ = x[Disj-3]
	_ = x[Cond-4]
	_ = x[Uni-5]
	_ = x[Ex-6]
	_ = x[Ident-7]
	_ = x[Nec-8]
	_ = x[Pos-9]
}

const _logicalConstant_name = "NoneNegConjDisjCondUniExIdentNecPos"

var _logicalConstant_index = [...]uint8{0, 4, 7, 11, 15, 19, 22, 24, 29, 32, 35}

func (i logicalConstant) String() string {
	if i < 0 || i >= logicalConstant(len(_logicalConstant_index)-1) {
		return "logicalConstant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _logicalConstant_name[_logicalConstant_index[i]:_logicalConstant_index[i+1]]
}
