// Code generated by "stringer -type logicalConstant"; DO NOT EDIT.

package gentzen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[noConstant-0]
	_ = x[neg-1]
	_ = x[conj-2]
	_ = x[disj-3]
	_ = x[cond-4]
	_ = x[uni-5]
	_ = x[ex-6]
	_ = x[ident-7]
	_ = x[nec-8]
	_ = x[pos-9]
}

const _logicalConstant_name = "NoneNegConjDisjCondUniExIdentNecPos"

var _logicalConstant_index = [...]uint8{0, 4, 7, 11, 15, 19, 22, 24, 29, 32, 35}

func (i logicalConstant) String() string {
	if i < 0 || i >= logicalConstant(len(_logicalConstant_index)-1) {
		return "logicalConstant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _logicalConstant_name[_logicalConstant_index[i]:_logicalConstant_index[i+1]]
}
