// Code generated by "stringer -type=PrintMode"; DO NOT EDIT.

package gentzen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[O_Polish-0]
	_ = x[O_Latex-1]
	_ = x[O_PlainLatex-2]
	_ = x[O_PlainText-3]
	_ = x[O_Simple-4]
	_ = x[O_English-5]
	_ = x[O_PlainASCII-6]
	_ = x[O_ProofChecker-7]
}

const _PrintMode_name = "O_PolishO_LatexO_PlainLatexO_PlainTextO_SimpleO_EnglishO_PlainASCIIO_ProofChecker"

var _PrintMode_index = [...]uint8{0, 8, 15, 27, 38, 46, 55, 67, 81}

func (i PrintMode) String() string {
	if i < 0 || i >= PrintMode(len(_PrintMode_index)-1) {
		return "PrintMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrintMode_name[_PrintMode_index[i]:_PrintMode_index[i+1]]
}
