package gentzen

import "strings"

func ltree(n *Node, simple bool) string {

	disp := func(k *Node) string {
		if k.Val.connective == None {
			return StringF(k, O_Latex)
		}
		return k.Val.connective.Stringf(O_Latex)
	}

	w := new(strings.Builder)

	ingressFunc := func(m *Node) {

		w.WriteString(`[\p{`)
		if simple {
			w.WriteString(disp(m))
		} else {
			w.WriteString(StringF(Parse(m.String(), !allowGreekUpper), O_Latex))
		}
		w.WriteString(`} `)
		w.WriteString("\n")
	}

	pivotFunc := func(m *Node) {

		w.WriteString(` ] `)
		w.WriteString("\n")
	}

	egressFunc := func(m *Node) {

		if !m.IsLastSibling() {
			return
		}

		w.WriteString(` ] `)
		w.WriteString("\n")
	}

	w.WriteString(`\begin{forest}` + "\n")
	w.WriteString(`%syntax tree of:` + "\n% " + n.String() + "\n")
	w.WriteString(`%generated by gentzen` + "\n")

	n.Walk(ingressFunc, pivotFunc, egressFunc)

	w.WriteString(`\end{forest}` + "\n\n")

	return w.String()

}

// SyntaxTree returns the latex code for printing the
// syntax tree of n. Each node will be printed as a full formula.
func SyntaxTree(n *Node) string {

	return ltree(n, false)

}

// SyntaxTreeSimple is like SyntaxTree but the nodes are represented by a single connective or, in the case leadnodes, by atomic sentence letters.
func SyntaxTreeSimple(n *Node) string {

	return ltree(n, true)

}
