// Code generated by "stringer -type=tokenID"; DO NOT EDIT.

package gentzen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tConj-1]
	_ = x[tDisj-2]
	_ = x[tNeg-4]
	_ = x[tCond-8]
	_ = x[tAtomicSentence-16]
	_ = x[tUni-32]
	_ = x[tEx-64]
	_ = x[tNec-128]
	_ = x[tPos-256]
	_ = x[tPredicate-512]
	_ = x[tTerm-1024]
	_ = x[tOpenb-2048]
	_ = x[tCloseb-4096]
	_ = x[tIdent-8192]
	_ = x[tComma-16384]
	_ = x[tNull-0]
	_ = x[tConnective-495]
	_ = x[tQuantifier-96]
	_ = x[tModalOperator-384]
	_ = x[tUnary-484]
	_ = x[tBinary-11]
}

const _tokenID_name = "tNulltConjtDisjtNegtCondtBinarytAtomicSentencetUnitExtQuantifiertNectPostModalOperatortUnarytConnectivetPredicatetTermtOpenbtClosebtIdenttComma"

var _tokenID_map = map[tokenID]string{
	0:     _tokenID_name[0:5],
	1:     _tokenID_name[5:10],
	2:     _tokenID_name[10:15],
	4:     _tokenID_name[15:19],
	8:     _tokenID_name[19:24],
	11:    _tokenID_name[24:31],
	16:    _tokenID_name[31:46],
	32:    _tokenID_name[46:50],
	64:    _tokenID_name[50:53],
	96:    _tokenID_name[53:64],
	128:   _tokenID_name[64:68],
	256:   _tokenID_name[68:72],
	384:   _tokenID_name[72:86],
	484:   _tokenID_name[86:92],
	495:   _tokenID_name[92:103],
	512:   _tokenID_name[103:113],
	1024:  _tokenID_name[113:118],
	2048:  _tokenID_name[118:124],
	4096:  _tokenID_name[124:131],
	8192:  _tokenID_name[131:137],
	16384: _tokenID_name[137:143],
}

func (i tokenID) String() string {
	if str, ok := _tokenID_map[i]; ok {
		return str
	}
	return "tokenID(" + strconv.FormatInt(int64(i), 10) + ")"
}
